Sacado_Wrapper::SW_double< dim > Class Template Reference
#include <Sacado_Wrapper.h>
Public Member Functions
SW_double & operator= (double double_init)
SW_double & operator= (fad_double fad_assignment)
void init (const double &double_init)
void set_dofs (unsigned int nbr_total_dofs=n_dofs)
void get_tangent (SymmetricTensor< 2, dim > &Tangent, SymmetricTensor< 2, dim, fad_double > &sigma)
void get_tangent (double &Tangent, fad_double &argument)
void get_values (double &return_double)
Public Attributes
unsigned int start_index = 0
Static Public Attributes
static const unsigned int n_dofs = 1
Member Function Documentation
get_tangent() [1/2]
template<int dim>
void Sacado_Wrapper::SW_double< dim >::get_tangent (SymmetricTensor< 2, dim > & Tangent, SymmetricTensor< 2, dim, fad_double > & sigma)
Referenced by sacado_test_4().
    {
        // reassemble the tangent as a SECOND order tensor
         for (unsigned int i=0; i<dim; ++i)
            for (unsigned int j=0; j<dim; ++j)
            {
                double *derivs = &sigma[i][j].fastAccessDx(0); // Access derivatives
                Tangent[i][j] = derivs[ this->start_index ]; // ToDo: check whether the 0.5* is
       necessary here too
            }
    }
get_tangent() [2/2]
template<int dim>
void Sacado_Wrapper::SW_double< dim >::get_tangent (double & Tangent, fad_double & argument)
    {
         double *derivs = &argument.fastAccessDx(0);
         Tangent = derivs[ this->start_index ];
    }
get_values()
template<int dim>
void Sacado_Wrapper::SW_double< dim >::get_values (double & return_double)
    {
        return_double = (*this).val();
    }
init()
template<int dim>
void Sacado_Wrapper::SW_double< dim >::init (const double & double_init)
Referenced by sacado_test_4().
    {
        (*this) = double_init;
    }
operator=() [1/2]
template<int dim>
SW_double& Sacado_Wrapper::SW_double< dim >::operator= (double double_init) [inline]
{ fad_double::operator =(double_init) ;return *this;}
operator=() [2/2]
template<int dim>
SW_double& Sacado_Wrapper::SW_double< dim >::operator= (fad_double fad_assignment) [inline]
{ fad_double::operator =(fad_assignment) ;return *this;}
set_dofs()
template<int dim>
void Sacado_Wrapper::SW_double< dim >::set_dofs (unsigned int nbr_total_dofs = n_dofs)
Referenced by Sacado_Wrapper::DoFs_summary< dim >::set_dofs().
    {
        (*this).diff(this->start_index, nbr_total_dofs);
    }
Member Data Documentation
n_dofs
template<int dim>
const unsigned int Sacado_Wrapper::SW_double< dim >::n_dofs = 1 [static]
Referenced by Sacado_Wrapper::DoFs_summary< dim >::set_dofs().
start_index
template<int dim>
unsigned int Sacado_Wrapper::SW_double< dim >::start_index = 0
Referenced by Sacado_Wrapper::DoFs_summary< dim >::set_dofs().
The documentation for this class was generated from the following file:
Sacado_Wrapper.h