Sacado_Wrapper::SW_double2< dim > Class Template Reference
#include <Sacado_Wrapper.h>
Public Member Functions
SW_double2 & operator= (double double_init)
SW_double2 & operator= (Sacado::Fad::DFad< DFadType > fad_assignment)
void init_set_dofs (const double &double_init, unsigned int nbr_total_dofs=n_dofs)
void get_tangent (double &Tangent, Sacado::Fad::DFad< DFadType > &argument)
void get_tangent (SymmetricTensor< 2, dim > &Tangent, SymmetricTensor< 2, dim, Sacado::Fad::DFad< DFadType > > &argument, SymTensor2< dim > &eps)
void get_curvature (double &Curvature, Sacado::Fad::DFad< DFadType > &argument)
void get_curvature (SymmetricTensor< 2, dim > &Curvature, SymmetricTensor< 2, dim, Sacado::Fad::DFad< DFadType > > &argument, SymTensor2< dim > &eps)
void get_curvature (SymmetricTensor< 2, dim > &Curvature, Sacado::Fad::DFad< DFadType > &argument, SymTensor2< dim > &eps)
Public Attributes
unsigned int start_index = 0
Static Public Attributes
static const unsigned int n_dofs = 1
Member Function Documentation
get_curvature() [1/3]
template<int dim>
void Sacado_Wrapper::SW_double2< dim >::get_curvature (double & Curvature, Sacado::Fad::DFad< DFadType > & argument)
Referenced by Sacado_Wrapper::DoFs_summary< dim >::get_curvature(), and sacado_test_8().
    {
        Curvature = argument.dx(this->start_index).dx(this->
      start_index);
    }
get_curvature() [2/3]
template<int dim>
void Sacado_Wrapper::SW_double2< dim >::get_curvature (SymmetricTensor< 2, dim > & Curvature, SymmetricTensor< 2, dim, Sacado::Fad::DFad< DFadType > > & argument, SymTensor2< dim > & eps)
References Sacado_Wrapper::SymTensor2< dim >::n_dofs, and Sacado_Wrapper::SymTensor2< dim >::std_map_indicies.
    {
        for(unsigned int x=0;x<eps.n_dofs;++x)
        {
            const unsigned int i=eps.std_map_indicies[x].first;
            const unsigned int j=eps.std_map_indicies[x].second;
// if (i!=j)
// Curvature[i][j] = 0.5 * argument[i][j].val().dx(start_index); // ToDo: check the factor
       0.5
// else
                Curvature[i][j] = argument[i][j].val().dx(start_index);
        }
    }
get_curvature() [3/3]
template<int dim>
void Sacado_Wrapper::SW_double2< dim >::get_curvature (SymmetricTensor< 2, dim > & Curvature, Sacado::Fad::DFad< DFadType > & argument, SymTensor2< dim > & eps)
References Sacado_Wrapper::SymTensor2< dim >::n_dofs, and Sacado_Wrapper::SymTensor2< dim >::std_map_indicies.
    {
        for(unsigned int x=0;x<eps.n_dofs;++x)
        {
            const unsigned int i=eps.std_map_indicies[x].first;
            const unsigned int j=eps.std_map_indicies[x].second;
            if (i!=j)
                Curvature[i][j] = 0.5 * argument.dx(start_index).dx(x); // ToDo: check the
       factor 0.5
            else
                Curvature[i][j] = argument.dx(start_index).dx(x);
        }
    }
get_tangent() [1/2]
template<int dim>
void Sacado_Wrapper::SW_double2< dim >::get_tangent (double & Tangent, Sacado::Fad::DFad< DFadType > & argument)
Referenced by sacado_test_8().
    {
        Tangent = argument.dx(this->start_index).val();
    }
get_tangent() [2/2]
template<int dim>
void Sacado_Wrapper::SW_double2< dim >::get_tangent (SymmetricTensor< 2, dim > & Tangent, SymmetricTensor< 2, dim, Sacado::Fad::DFad< DFadType > > & argument, SymTensor2< dim > & eps)
References Sacado_Wrapper::SymTensor2< dim >::n_dofs, and Sacado_Wrapper::SymTensor2< dim >::std_map_indicies.
    {
        for(unsigned int x=0;x<eps.n_dofs;++x)
        {
            const unsigned int i=eps.std_map_indicies[x].first;
            const unsigned int j=eps.std_map_indicies[x].second;
            // ToDo: find a better way to loop over the indices than using eps as input argument
            Tangent[i][j] = argument[i][j].dx(start_index).val();
        }
    }
init_set_dofs()
template<int dim>
void Sacado_Wrapper::SW_double2< dim >::init_set_dofs (const double & double_init, unsigned int nbr_total_dofs = n_dofs)
Referenced by Sacado_Wrapper::DoFs_summary< dim >::init_set_dofs().
    {
        (*this).diff(start_index , nbr_total_dofs);
        (*this).val() = fad_double(nbr_total_dofs, start_index, double_init);
    }
operator=() [1/2]
template<int dim>
SW_double2& Sacado_Wrapper::SW_double2< dim >::operator= (double double_init) [inline]
{ Sacado::Fad::DFad<DFadType>::operator =(double_init) ;return *this;}
operator=() [2/2]
template<int dim>
SW_double2& Sacado_Wrapper::SW_double2< dim >::operator= (Sacado::Fad::DFad< DFadType > fad_assignment) [inline]
{ Sacado::Fad::DFad<DFadType>::operator =(fad_assignment) ;return *this;}
Member Data Documentation
n_dofs
template<int dim>
const unsigned int Sacado_Wrapper::SW_double2< dim >::n_dofs = 1 [static]
Referenced by Sacado_Wrapper::DoFs_summary< dim >::init_set_dofs().
start_index
template<int dim>
unsigned int Sacado_Wrapper::SW_double2< dim >::start_index = 0
Referenced by Sacado_Wrapper::DoFs_summary< dim >::init_set_dofs().
The documentation for this class was generated from the following file:
Sacado_Wrapper.h