Sacado_Wrapper::DoFs_summary< dim > Class Template Reference
#include <Sacado_Wrapper.h>
Public Member Functions
void set_dofs (SymTensor< dim > &eps, SW_double< dim > &double_arg)
void init_set_dofs (SymTensor2< dim > &eps, SymmetricTensor< 2, dim > &eps_init, SW_double2< dim > &double_arg, double &double_init)
void get_curvature (SymmetricTensor< 2, dim > &Curvature, Sacado::Fad::DFad< DFadType > &argument, SymTensor2< dim > &eps, SW_double2< dim > &double_arg)
void get_curvature (SymmetricTensor< 2, dim > &Curvature, Sacado::Fad::DFad< DFadType > &argument, SW_double2< dim > &double_arg, SymTensor2< dim > &eps)
void set_dofs (SymTensor< dim > &eps, SW_double< dim > &double_arg1, SW_double< dim > &double_arg2, SW_double< dim > &double_arg3)
void set_dofs (SymTensor< dim > &eps, SW_double< dim > &double_arg1, SW_double< dim > &double_arg2)
Member Function Documentation
get_curvature() [1/2]
template<int dim>
void Sacado_Wrapper::DoFs_summary< dim >::get_curvature (SymmetricTensor< 2, dim > & Curvature, Sacado::Fad::DFad< DFadType > & argument, SymTensor2< dim > & eps, SW_double2< dim > & double_arg)
References Sacado_Wrapper::SW_double2< dim >::get_curvature(), and Sacado_Wrapper::SymTensor2< dim >::get_tangent().
Referenced by sacado_test_8().
    {
        SymmetricTensor<2,dim, Sacado::Fad::DFad<DFadType> > d_arg_d_eps;
        eps.get_tangent(d_arg_d_eps, argument);
        double_arg.get_curvature(Curvature, d_arg_d_eps, eps);
    }
get_curvature() [2/2]
template<int dim>
void Sacado_Wrapper::DoFs_summary< dim >::get_curvature (SymmetricTensor< 2, dim > & Curvature, Sacado::Fad::DFad< DFadType > & argument, SW_double2< dim > & double_arg, SymTensor2< dim > & eps)
References Sacado_Wrapper::SW_double2< dim >::get_curvature().
    {
        double_arg.get_curvature(Curvature, argument, eps);
    }
init_set_dofs()
template<int dim>
void Sacado_Wrapper::DoFs_summary< dim >::init_set_dofs (SymTensor2< dim > & eps, SymmetricTensor< 2, dim > & eps_init, SW_double2< dim > & double_arg, double & double_init)
References Sacado_Wrapper::SymTensor2< dim >::init_set_dofs(), Sacado_Wrapper::SW_double2< dim >::init_set_dofs(), Sacado_Wrapper::SymTensor2< dim >::n_dofs, Sacado_Wrapper::SW_double2< dim >::n_dofs, Sacado_Wrapper::SymTensor2< dim >::start_index, and Sacado_Wrapper::SW_double2< dim >::start_index.
Referenced by sacado_test_8().
    {
        const unsigned int nbr_total_dofs = eps.n_dofs + double_arg.n_dofs;
        eps.start_index = 0;
        double_arg.start_index = eps.n_dofs;
        
        eps.init_set_dofs(eps_init, nbr_total_dofs);
        double_arg.init_set_dofs(double_init, nbr_total_dofs);
    }
set_dofs() [1/3]
template<int dim>
void Sacado_Wrapper::DoFs_summary< dim >::set_dofs (SymTensor< dim > & eps, SW_double< dim > & double_arg)
References Sacado_Wrapper::SymTensor< dim >::n_dofs, Sacado_Wrapper::SW_double< dim >::n_dofs, Sacado_Wrapper::SymTensor< dim >::set_dofs(), Sacado_Wrapper::SW_double< dim >::set_dofs(), Sacado_Wrapper::SymTensor< dim >::start_index, and Sacado_Wrapper::SW_double< dim >::start_index.
Referenced by sacado_test_4().
    {
        const unsigned int nbr_total_dofs = eps.n_dofs + double_arg.n_dofs;
        eps.start_index = 0;
        double_arg.start_index = eps.n_dofs;
        eps.set_dofs(nbr_total_dofs);
        double_arg.set_dofs(nbr_total_dofs);
    }
set_dofs() [2/3]
template<int dim>
void Sacado_Wrapper::DoFs_summary< dim >::set_dofs (SymTensor< dim > & eps, SW_double< dim > & double_arg1, SW_double< dim > & double_arg2, SW_double< dim > & double_arg3)
References Sacado_Wrapper::SymTensor< dim >::n_dofs, Sacado_Wrapper::SW_double< dim >::n_dofs, Sacado_Wrapper::SymTensor< dim >::set_dofs(), Sacado_Wrapper::SW_double< dim >::set_dofs(), Sacado_Wrapper::SymTensor< dim >::start_index, and Sacado_Wrapper::SW_double< dim >::start_index.
    {
        const unsigned int nbr_total_dofs = eps.n_dofs + double_arg1.n_dofs + double_arg2.n_dofs +
      double_arg3.n_dofs ;
        eps.start_index = 0;
        double_arg1.start_index = eps.n_dofs;
        double_arg2.start_index = eps.n_dofs + double_arg1.n_dofs;
        double_arg3.start_index = eps.n_dofs + double_arg1.n_dofs + double_arg2.n_dofs;
        eps.set_dofs(nbr_total_dofs);
        double_arg1.set_dofs(nbr_total_dofs);
        double_arg2.set_dofs(nbr_total_dofs);
        double_arg3.set_dofs(nbr_total_dofs);
    }
set_dofs() [3/3]
template<int dim>
void Sacado_Wrapper::DoFs_summary< dim >::set_dofs (SymTensor< dim > & eps, SW_double< dim > & double_arg1, SW_double< dim > & double_arg2)
References Sacado_Wrapper::SymTensor< dim >::n_dofs, Sacado_Wrapper::SW_double< dim >::n_dofs, Sacado_Wrapper::SymTensor< dim >::set_dofs(), Sacado_Wrapper::SW_double< dim >::set_dofs(), Sacado_Wrapper::SymTensor< dim >::start_index, and Sacado_Wrapper::SW_double< dim >::start_index.
    {
        const unsigned int nbr_total_dofs = eps.n_dofs + double_arg1.n_dofs + double_arg2.n_dofs ;
        eps.start_index = 0;
        double_arg1.start_index = eps.n_dofs;
        double_arg2.start_index = eps.n_dofs + double_arg1.n_dofs;
        eps.set_dofs(nbr_total_dofs);
        double_arg1.set_dofs(nbr_total_dofs);
        double_arg2.set_dofs(nbr_total_dofs);
    }
The documentation for this class was generated from the following file:
Sacado_Wrapper.h