Sacado_Wrapper::SymTensor2< dim > Class Template Reference
#include <Sacado_Wrapper.h>
Public Member Functions
SymTensor2 ()
void init_set_dofs (SymmetricTensor< 2, dim > &tensor_double, const unsigned int nbr_total_dofs=n_dofs)
void get_tangent (SymmetricTensor< 4, dim > &Tangent, SymmetricTensor< 2, dim, Sacado::Fad::DFad< DFadType > > &sigma)
void get_tangent (SymmetricTensor< 2, dim > &Tangent, Sacado::Fad::DFad< DFadType > &argument)
void get_tangent (SymmetricTensor< 2, dim, Sacado::Fad::DFad< DFadType > > &Tangent, Sacado::Fad::DFad< DFadType > &argument)
void get_curvature (SymmetricTensor< 4, dim > &Curvature, Sacado::Fad::DFad< DFadType > &argument)
Public Attributes
std::map< unsigned int, std::pair< unsigned int, unsigned int > > std_map_indicies
unsigned int start_index = 0
Static Public Attributes
static const unsigned int n_dofs = ((dim==2)?3:6)
Constructor & Destructor Documentation
template<int dim> Sacado_Wrapper::SymTensor2< dim >::SymTensor2 () [inline]
        {
            get_index_map<dim>(std_map_indicies);
        }
Member Function Documentation
template<int dim> void Sacado_Wrapper::SymTensor2< dim >::get_curvature (SymmetricTensor< 4, dim > & Curvature, Sacado::Fad::DFad< DFadType > & argument)
    {
         for(unsigned int x=0;x<n_dofs;++x)
            for(unsigned int y=0;y<n_dofs;++y)
            {
                const unsigned int i=std_map_indicies[y].first;
                const unsigned int j=std_map_indicies[y].second;
                const unsigned int k=std_map_indicies[x].first;
                const unsigned int l=std_map_indicies[x].second;
                double deriv = argument.dx(x).dx(y); // Access the derivatives of the (i,j)-th component of
       \a sigma
                if (k!=l && i!=j)
                    Curvature[i][j][k][l] = 0.25* deriv;
                else if(k!=l)/*Compare to Voigt notation since only SymmetricTensor instead of Tensor*/
                {
                    Curvature[i][j][k][l] = 0.5*deriv;
                    Curvature[i][j][l][k] = 0.5*deriv;
                }
                else
                    Curvature[i][j][k][l] = deriv;
            }
    }
template<int dim> void Sacado_Wrapper::SymTensor2< dim >::get_tangent (SymmetricTensor< 4, dim > & Tangent, SymmetricTensor< 2, dim, Sacado::Fad::DFad< DFadType > > & sigma)
Referenced by Sacado_Wrapper::DoFs_summary< dim >::get_curvature().
    {
         for(unsigned int x=0;x<n_dofs;++x)
            for(unsigned int y=0;y<n_dofs;++y)
            {
                const unsigned int i=std_map_indicies[y].first;
                const unsigned int j=std_map_indicies[y].second;
                const unsigned int k=std_map_indicies[x].first;
                const unsigned int l=std_map_indicies[x].second;
                if(k!=l)/*Compare to Voigt notation since only SymmetricTensor instead of Tensor*/
                    Tangent[i][j][k][l] = 0.5 * argument[k][l].dx(y).val(); // ToDo: check this on
       paper (was more like a gut feeling)
                else
                    Tangent[i][j][k][l] = argument[k][l].dx(y).val();
            }
    }
template<int dim> void Sacado_Wrapper::SymTensor2< dim >::get_tangent (SymmetricTensor< 2, dim > & Tangent, Sacado::Fad::DFad< DFadType > & argument)
    {
        for (unsigned int x=0; x<n_dofs; ++x)
         {
            unsigned int i=std_map_indicies[x].first;
            unsigned int j=std_map_indicies[x].second;
            if (i!=j)
                Tangent[i][j] = 0.5 * argument.dx(x).val();
            else
                Tangent[i][j] = argument.dx(x).val();
         }
    }
template<int dim> void Sacado_Wrapper::SymTensor2< dim >::get_tangent (SymmetricTensor< 2, dim, Sacado::Fad::DFad< DFadType > > & Tangent, Sacado::Fad::DFad< DFadType > & argument)
    {
        for (unsigned int x=0; x<n_dofs; ++x)
         {
            unsigned int i=std_map_indicies[x].first;
            unsigned int j=std_map_indicies[x].second;
            if (i!=j)
                Tangent[i][j] = 0.5 * argument.dx(x);
            else
                Tangent[i][j] = argument.dx(x);
         }
    }
template<int dim> void Sacado_Wrapper::SymTensor2< dim >::init_set_dofs (SymmetricTensor< 2, dim > & tensor_double, const unsigned int nbr_total_dofs = n_dofs)
Referenced by Sacado_Wrapper::DoFs_summary< dim >::init_set_dofs().
    {
         for (unsigned int x=0; x<n_dofs; ++x)
         {
            unsigned int i=std_map_indicies[x].first;
            unsigned int j=std_map_indicies[x].second;
            ((*this)[i][j]).diff(x, nbr_total_dofs); // set up the "inner" derivatives
            ((*this)[i][j]).val() = fad_double(nbr_total_dofs, x, tensor_double[i][j]); // set up
       the "outer" derivatives
         }
    }
Member Data Documentation
template<int dim> const unsigned int Sacado_Wrapper::SymTensor2< dim >::n_dofs = ((dim==2)?3:6) [static]
Referenced by Sacado_Wrapper::SW_double2< dim >::get_curvature(), Sacado_Wrapper::SW_double2< dim >::get_tangent(), and Sacado_Wrapper::DoFs_summary< dim >::init_set_dofs().
template<int dim> unsigned int Sacado_Wrapper::SymTensor2< dim >::start_index = 0
Referenced by Sacado_Wrapper::DoFs_summary< dim >::init_set_dofs().
template<int dim> std::map<unsigned int,std::pair<unsigned int,unsigned int> > Sacado_Wrapper::SymTensor2< dim >::std_map_indicies
Referenced by Sacado_Wrapper::SW_double2< dim >::get_curvature(), and Sacado_Wrapper::SW_double2< dim >::get_tangent().
The documentation for this class was generated from the following file:
Sacado_Wrapper.h